### ISSUE TITLE
Property 'toasts' does not exist on type 'IntrinsicAttributes & ToastContainerProps'.

### ISSUE THREAD

**Issue by www-chique** [mzohaibqc/svelte-toasts#1]
I am really a fan of this package and trying to use it in my application.
However, I get this typescript error.

![image](https://user-images.githubusercontent.com/29447216/111250968-56589780-8634-11eb-8ac0-97452ce7e305.png)

If I ignore, it just works fine. But it would be great to also not have this error message.
Also getting the same error at "width" property.
![image](https://user-images.githubusercontent.com/29447216/111251076-8ef87100-8634-11eb-9966-00ea6a532d73.png)

Am I doing something wrong? 
Many thanks and I appreciate your work.

**Comment by mzohaibqc** [comment]
@www-chique Thanks for your kind words.

That's my mistake, ToastContainer does not take `toasts` prop as store. It is importting `toasts` from store inside that component so no need to add that prop. I've updated the docs on website.

width type was `'string'` which was incorrect so fixed it. now it is `string` so it will work. 

You can update npm package to `svelte-toasts@1.1.2` and everything will be good.
